name: Hello Github Actions
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: CloudComputing
    steps:
      - name: Say Hello
        run: echo "Hello from ${COURSE}!!!!!!!!!!"
      - run: echo "I'll list files."
      - run: ls -al
  goodbye:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye from ${COURSE}"
      - run: echo "${{ secrets.MY_SECRET }}"
      
